"""rename department

Revision ID: 7bed7057ec54
Revises: ddcf9197aad6
Create Date: 2024-04-08 16:16:45.999453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bed7057ec54'
down_revision = 'ddcf9197aad6'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('departments',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('name', sa.String(), nullable=False),
#     sa.Column('address', sa.String(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.drop_table('department')
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('department',
#     sa.Column('id', sa.INTEGER(), nullable=False),
#     sa.Column('name', sa.VARCHAR(), nullable=False),
#     sa.Column('address', sa.VARCHAR(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.drop_table('departments')
#     # ### end Alembic commands ###

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###