"""rename address

Revision ID: 89dd3ad8e4c5
Revises: 7bed7057ec54
Create Date: 2024-04-08 16:25:41.276736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89dd3ad8e4c5'
down_revision = '7bed7057ec54'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('departments', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('location', sa.String(), nullable=False))
#         batch_op.drop_column('address')

#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('departments', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=True))
#         batch_op.drop_column('location')

#     # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###